### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by zupat** [beenotung/better-sql#1]
I think I have a interesting idea for this project that could render edgedb redundant...

In addition to generating sql, how about letting the user write the query they want in better SQL and generate  a PG schema that can support that query?

**Comment by beenotung** [comment]
I made a tool [1] to generate (sql or knex migrate) scripts that create tables.
But it's using a table definition language, not a query.

The problem to create table from query is you may not be able to know the data type of each column.

[1] https://github.com/beenotung/quick-erd

**Comment by jinyus** [comment]
I see, would be awesome though...
Great job on the erd tool

**Comment by beenotung** [comment]
Welcome your interesting ideas anyway :)
